### ISSUE TITLE
Deregistering chain module socket close

### ISSUE THREAD

**Issue by neppinger** [Verady/veranet#2]
### Package Version

Replace the value below using the output from `veranet --version`.

```
veranet  1.0.0
protocol 1.0.0
```

Replace the value below using the output from `node --version`.

```
v8.9.1
```

### Expected Behavior

Chain module would close the socket if the underlying chain module exists 

### Actual Behavior
{"name":"c3190409fb5bce049dec76eb2e3a686a9e2b4917","hostname":"ip-192-168-10-110.ec2.internal","pid":55480,"level":50,"msg":"mod.socket.close is not a function","time":"2018-02-11T19:52:24.912Z","v":0}
{"name":"c3190409fb5bce049dec76eb2e3a686a9e2b4917","hostname":"ip-192-168-10-110.ec2.internal","pid":55480,"level":20,"msg":"TypeError: mod.socket.close is not a function\n    at Node.deregisterModule (/Users/neppinger/Work/verady/kad-veranet/veranet/lib/node.js:365:16)\n    at Socket.client.socket.once (/Users/neppinger/Work/verady/kad-veranet/veranet/lib/node.js:316:12)\n    at Object.onceWrapper (events.js:316:30)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at Pipe._handle.close [as _onclose] (net.js:547:12)","time":"2018-02-11T19:52:24.912Z","v":0}

### Steps to Reproduce

1. Register a chain module
2. kill the chain module process

Not sure if the socket needs to be closed. I've run with removing the line without any issues.

**Comment by 161chihuahuas** [comment]
It's a typo, should have been `Socket#destroy` instead of `Socket#close`
